# Use ubi8-init image
FROM redhat/ubi8

# Update and upgrade packages
RUN yum update -y && yum upgrade -y

# Install python and pip
RUN yum install -y python3 python3-pip

# Clean caché
RUN yum clean all

# Version
LABEL version="1.1"

# Author
LABEL maintainer="Javier Moreno Sánchez"

