FROM agss_debian-systemd:v1

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y gnupg curl sudo python3-pip

RUN curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | \
   gpg -o /usr/share/keyrings/mongodb-server-4.4.gpg \
   --dearmor

RUN echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y mongodb-org mongosh
RUN pip install pymongo
RUN apt-get clean

RUN systemctl start mongodb
EXPOSE 27017
