# Use ubi8-init image
FROM redhat/ubi8

# Update and upgrade packages
RUN yum update -y && yum upgrade -y

# Install sudo
RUN yum install -y sudo

# Install python and pip
RUN yum install -y python3 python3-pip

# Install necessary packages to mysql
RUN yum install -y https://rpmfind.net/linux/epel/7/x86_64/Packages/l/libpmem-1.1-1.el7.x86_64.rpm

RUN yum install -y https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/boost-program-options-1.66.0-10.el8.x86_64.rpm

# Clean caché
RUN yum clean all

# Version
LABEL version="1.2"

# Author
LABEL maintainer="Javier Moreno Sánchez"

