# Use ubi8-init image
FROM centos:7

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

# Update and upgrade packages
RUN yum update -y && yum upgrade -y

# Install sudo
RUN yum install -y sudo

# Install python and pip
RUN yum install -y python3 python3-pip

# Clean caché
RUN yum clean all

# Version
LABEL version="1.0"

# Author
LABEL maintainer="Javier Moreno Sánchez"

