# Use Ubi8-python image
FROM ubi8-python:v1

# Update and upgrade packages and repos
RUN yum update && yum upgrade -y

# Install httpd
RUN yum install httpd -y

# Clean cache
RUN yum clean all

# Open port 80
EXPOSE 80

# Define version tag
LABEL version="v1"

# Define author
LABEL maintainer="Javier Moreno Sánchez"

