# Use Debian 11.9 image
FROM debian:11.9

# Update and upgrade packages and repos
RUN apt-get update && apt-get upgrade -y

# Install sudo
RUN apt-get install -y sudo

# Install Python and pip
RUN apt-get install -y python3 python3-pip python3-mysqldb

# Install mysql
RUN apt-get install -y mariadb-server

# Clean cache
RUN apt-get clean

ENV MARIADB_ROOT_PASSWORD=vagrant

# Copy config file
COPY 50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

# Open port 3306
EXPOSE 3306

# Start mariadb service
RUN service mariadb restart

# Define version tag
LABEL version="11.9"

# Define author
LABEL maintainer="Javier Moreno Sánchez"

